# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/xray_api/stats.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app/xray_api/stats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61pp/xray_api/stats.proto\x12\x16xray.app.stats.command\"#\n\x04Stat\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03\".\n\x0fGetStatsRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05reset\x18\x02 \x01(\x08\">\n\x10GetStatsResponse\x12*\n\x04stat\x18\x01 \x01(\x0b\x32\x1c.xray.app.stats.command.Stat\"3\n\x11QueryStatsRequest\x12\x0f\n\x07pattern\x18\x01 \x01(\t\x12\r\n\x05reset\x18\x02 \x01(\x08\"@\n\x12QueryStatsResponse\x12*\n\x04stat\x18\x01 \x03(\x0b\x32\x1c.xray.app.stats.command.Stat\"\x11\n\x0fSysStatsRequest\"\xc3\x01\n\x10SysStatsResponse\x12\x14\n\x0cNumGoroutine\x18\x01 \x01(\x03\x12\r\n\x05NumGC\x18\x02 \x01(\x03\x12\r\n\x05\x41lloc\x18\x03 \x01(\x03\x12\x12\n\nTotalAlloc\x18\x04 \x01(\x03\x12\x0b\n\x03Sys\x18\x05 \x01(\x03\x12\x0f\n\x07Mallocs\x18\x06 \x01(\x03\x12\r\n\x05\x46rees\x18\x07 \x01(\x03\x12\x13\n\x0bLiveObjects\x18\x08 \x01(\x03\x12\x15\n\rPausedTotalNs\x18\t \x01(\x03\x12\x0e\n\x06Uptime\x18\n \x01(\x05\x32\xba\x02\n\x0cStatsService\x12_\n\x08GetStats\x12\'.xray.app.stats.command.GetStatsRequest\x1a(.xray.app.stats.command.GetStatsResponse\"\x00\x12\x65\n\nQueryStats\x12).xray.app.stats.command.QueryStatsRequest\x1a*.xray.app.stats.command.QueryStatsResponse\"\x00\x12\x62\n\x0bGetSysStats\x12\'.xray.app.stats.command.SysStatsRequest\x1a(.xray.app.stats.command.SysStatsResponse\"\x00\x42%Z#xray.website/core/app/stats/commandb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.xray_api.stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#xray.website/core/app/stats/command'
  _globals['_STAT']._serialized_start=52
  _globals['_STAT']._serialized_end=87
  _globals['_GETSTATSREQUEST']._serialized_start=89
  _globals['_GETSTATSREQUEST']._serialized_end=135
  _globals['_GETSTATSRESPONSE']._serialized_start=137
  _globals['_GETSTATSRESPONSE']._serialized_end=199
  _globals['_QUERYSTATSREQUEST']._serialized_start=201
  _globals['_QUERYSTATSREQUEST']._serialized_end=252
  _globals['_QUERYSTATSRESPONSE']._serialized_start=254
  _globals['_QUERYSTATSRESPONSE']._serialized_end=318
  _globals['_SYSSTATSREQUEST']._serialized_start=320
  _globals['_SYSSTATSREQUEST']._serialized_end=337
  _globals['_SYSSTATSRESPONSE']._serialized_start=340
  _globals['_SYSSTATSRESPONSE']._serialized_end=535
  _globals['_STATSSERVICE']._serialized_start=538
  _globals['_STATSSERVICE']._serialized_end=852
# @@protoc_insertion_point(module_scope)
